spring.application.name=spring-payments
payments.fraud-check.enabled=false
spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT:5435}/payments
spring.datasource.username=payments
spring.datasource.password=payments
spring.jpa.hibernate.ddl-auto=create-drop
payments.fee-basis-points=150
