payments.fraud-check.enabled=false
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:${POSTGRES_PORT:5435}/payments
quarkus.datasource.username=payments
quarkus.datasource.password=payments
quarkus.datasource.devservices.enabled=false
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
payments.fee-basis-points=150
